# Generated by Django 4.2.4 on 2023-11-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibleperson',
            name='passport_serial',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
