# Generated by Django 4.2.4 on 2023-10-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryunit",
            name="district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_unit_for_district",
                to="dictionary.district",
            ),
            preserve_default=False,
        ),
    ]
