# Generated by Django 4.2.4 on 2023-10-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventoryunit_district"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="writeoffact",
            options={},
        ),
        migrations.AddField(
            model_name="writeoffact",
            name="name_ru",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="writeoffact",
            name="name_uz",
            field=models.CharField(default="akt 001", max_length=200),
            preserve_default=False,
        ),
    ]
