# Generated by Django 4.2.4 on 2023-10-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_writeoffact_options_writeoffact_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryunit",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
