# Generated by Django 4.2.4 on 2023-11-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryunit_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'year')},
        ),
    ]
