# Generated by Django 4.2.4 on 2023-11-27 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_year'),
        ('inventory', '0005_alter_productprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='productnorm',
            options={},
        ),
        migrations.RemoveField(
            model_name='productnorm',
            name='count',
        ),
        migrations.AlterField(
            model_name='productprice',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_for_product_price', to='dictionary.year'),
        ),
        migrations.AddConstraint(
            model_name='productnorm',
            constraint=models.UniqueConstraint(condition=models.Q(('district__isnull', False)), fields=('product', 'region', 'district'), name='unique_region_product_with_district'),
        ),
        migrations.AddConstraint(
            model_name='productnorm',
            constraint=models.UniqueConstraint(condition=models.Q(('district__isnull', True)), fields=('product', 'region'), name='unique_region_product_without_district'),
        ),
        migrations.AddField(
            model_name='annualnorm',
            name='product_norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_norm_for_product_norm', to='inventory.productnorm'),
        ),
        migrations.AddField(
            model_name='annualnorm',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_for_annual_norm', to='dictionary.year'),
        ),
        migrations.AlterUniqueTogether(
            name='annualnorm',
            unique_together={('product_norm', 'year')},
        ),
    ]
